# Aula 1: Introdução ao Numpy e Pandas

## Listas

In [1]:
lista = [1, 2, 3, 4, 5]
lista

[1, 2, 3, 4, 5]

In [2]:
list(range(1,6))

[1, 2, 3, 4, 5]

In [3]:
lista.append(6)
lista

[1, 2, 3, 4, 5, 6]

In [4]:
del lista[0]

In [5]:
lista

[2, 3, 4, 5, 6]

In [6]:
lista.index(6)

4

In [7]:
del lista[lista.index(6)]

In [8]:
lista

[2, 3, 4, 5]

In [12]:
4 in lista

False

In [11]:
lista.remove(4)

In [13]:
type(lista)

list

In [36]:
lista = [1, 1, 1, 2, 3, 4, 5, 1, 2, 1]

lista

[1, 1, 1, 2, 3, 4, 5, 1, 2, 1]

In [35]:
lista.remove(1)

ValueError: list.remove(x): x not in list

In [16]:
lista

[1, 1, 2, 3, 4, 5, 1, 2, 1]

In [18]:
del lista[lista.index(1)]

In [19]:
lista

[1, 1, 2, 3, 4, 5, 1, 2, 1]

In [33]:
aux = []
for i in lista:
    if i == 1:
        lista.remove(i)
        

In [37]:
while 1 in lista:
    lista.remove(1)

In [38]:
lista

[2, 3, 4, 5, 2]

In [27]:
list(filter(lambda x: x!=1, lista))

[2, 3, 4, 5, 2]

In [ ]:
remove_hum = lambda x: x !=1 

In [ ]:
def remove_hum(x):
    return x!=1  

### List comprehension

In [40]:
zeros = []
for i in range(10):
    zeros.append(0)
    
zeros

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
1
[0, ]
[0, 0, , ]
[0, 0, 0, ]
[0, 0, 0,0]
[0, 0, 0, 0, , , , , , ] 16 posições - 6 delas desocupadas



In [43]:
zeros = [0 for i in range(10)]
zeros

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [44]:
lista = list(range(10))

In [45]:
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [46]:
lista[0] += 1

In [49]:
for i in range(len(lista)):
    lista[i] += 1
    
lista

[2, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [51]:
lista1 = lista[:len(lista)//2]
lista2 = lista[len(lista)//2:]


In [56]:
lista1 + lista2

[2, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [53]:
lista2

[6, 7, 8, 9, 10]

In [57]:
lista3 = []
for i in range(len(lista1)):
    lista3.append(lista1[i]+lista2[i])

In [58]:
lista3

[8, 9, 11, 13, 15]

In [59]:
lista3 = [lista1[i]+lista2[i] for i in range(len(lista1))]

In [60]:
lista3

[8, 9, 11, 13, 15]

In [61]:
lista = list(range(1, 6))
lista[1] += 1
lista

[1, 3, 3, 4, 5]

In [62]:
lista = list(range(1, 6))
print('antes  -', lista)
lista = [elemento*5 for elemento in lista]
print('depois -',lista)

antes  - [1, 2, 3, 4, 5]
depois - [5, 10, 15, 20, 25]


In [77]:
lista3 = lista[:] # ou lista.copy()

In [78]:
lista3.append(3)

In [79]:
print(id(lista))
print(id(lista3))

1865421289600
1865421876544


In [81]:
lista3

[5, 10, 15, 20, 25, 3, 3]

In [84]:
list(map(lambda x, y: x+y, lista1, lista2))

[8, 9, 11, 13, 15]

In [ ]:
def soma_dois_num(x, y):
    return x+y

In [85]:
[x+y for x,y in zip(lista1, lista2)]

[8, 9, 11, 13, 15]

In [87]:
list(zip(lista1, lista2))

[(2, 6), (2, 7), (3, 8), (4, 9), (5, 10)]

In [89]:
[x+lista2[idx] for idx, x in enumerate(lista1)]

[8, 9, 11, 13, 15]

In [91]:
lista1

[2, 2, 3, 4, 5]

In [90]:
list(enumerate(lista1))

[(0, 2), (1, 2), (2, 3), (3, 4), (4, 5)]

In [121]:
import random

In [124]:
random.seed()

In [125]:
random.random()

0.8587809941212687

## Numpy

In [127]:
import numpy as np

Numpy é uma biblioteca das principais bibliotecas do Python, devido a sua grande velocidade e eficiência ele é extremamente utilizada para computação científica e analise de dados. Esta fama se da principalmente a estrutura chamada [numpy array](https://docs.scipy.org/doc/numpy/reference/arrays.html), um forma eficiente de guardar e manipular matrizes, que serve como base para as tabelas que iremos utilizar.

In [130]:
# criando listas numpy a partir de listas do python
lista = [1,2,3,4,5]
listaNumpy = np.array(lista)
print(type(listaNumpy))
listaNumpy


<class 'numpy.ndarray'>


array([1, 2, 3, 4, 5])

In [131]:
[0 for i in range(10)]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [132]:
#Criando array zeros nump
zeros = np.zeros(10)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [139]:
#Criando array 1 
uns = np.ones(10)
uns

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Multiplicação de Listas vs np.Array

In [142]:
uns = [1 for i in range(10)]

[x*5 for x in uns]

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]

In [144]:
uns = np.ones(10)
uns

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [147]:
cincos = uns*5
cincos

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [148]:
#Criando array de um numero qualquer
cincos = (np.ones(10) + 5)*3/2
cincos

array([9., 9., 9., 9., 9., 9., 9., 9., 9., 9.])

In [149]:
list(range(0, 11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [150]:
#Criando array com sequencia
lista10 = np.arange(0,11)
lista10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [157]:
list(range(0, 20, 2))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [154]:
#Criando lista Com saltos
listaD = np.arange(0,20,2)
listaD

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [158]:
x = 2/20
[x*i for i in range(0, 21)]

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9,
 1.0,
 1.1,
 1.2000000000000002,
 1.3,
 1.4000000000000001,
 1.5,
 1.6,
 1.7000000000000002,
 1.8,
 1.9000000000000001,
 2.0]

In [161]:
#Array espaçado, os dois primeiros numeros são o intervalo, o terceiro e numero de valores 
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [167]:
from numpy import random

#Criando array com valores aleatorios
aleatorio = np.random.rand(10)
aleatorio

array([0.90805638, 0.27039337, 0.36225524, 0.090164  , 0.5842202 ,
       0.19610643, 0.99694498, 0.52489665, 0.22821104, 0.49854184])

In [168]:
# aleatorio inteiro (10 itens de 0 a 100)
lista1 = np.random.randint(0,100,10)
lista1

array([ 6, 96, 36, 23, 19, 10, 36, 42, 72, 36])

In [171]:
import random
np.array(random.sample(range(100), 10))

array([10, 75, 19, 45, 76, 51, 46, 48, 20,  3])

### Indexação

In [177]:
lista = list(range(10))
lista

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [183]:
lista[5:2:-1]

[5, 4, 3]

In [184]:
lista10

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [185]:
lista10[5]

5

In [187]:
#Partindo array
lista10[2:7]

array([2, 3, 4, 5, 6])

In [188]:
parte = lista10[3:8:2]
parte

array([3, 5, 7])

In [189]:
#Criando array com sequencia
lista40 = np.arange(10,50)
lista40

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

### Operações simples

In [190]:
lista1

array([ 6, 96, 36, 23, 19, 10, 36, 42, 72, 36])

In [191]:
listaLista1 = list(lista1)
listaLista1

[6, 96, 36, 23, 19, 10, 36, 42, 72, 36]

In [192]:
lista1 * 2

array([ 12, 192,  72,  46,  38,  20,  72,  84, 144,  72])

In [193]:
listaLista1 * 2

[6, 96, 36, 23, 19, 10, 36, 42, 72, 36, 6, 96, 36, 23, 19, 10, 36, 42, 72, 36]

In [198]:
lista1 + 1

array([ 7, 97, 37, 24, 20, 11, 37, 43, 73, 37])

In [199]:
lista1 ** 2

array([  36, 9216, 1296,  529,  361,  100, 1296, 1764, 5184, 1296],
      dtype=int32)

In [200]:
lista1 / 2

array([ 3. , 48. , 18. , 11.5,  9.5,  5. , 18. , 21. , 36. , 18. ])

In [201]:
lista1 // 2

array([ 3, 48, 18, 11,  9,  5, 18, 21, 36, 18], dtype=int32)

In [205]:
lista1 = np.array(lista1)
lista1

array([ 6, 96, 36, 23, 19, 10, 36, 42, 72, 36])

### Operações com Arrays

In [207]:
array1 = np.random.randint(0,100,10)
array2 = np.random.randint(0,100,10)
print(array1, type(lista1))
print(array2, type(lista2))

[66 36 53 95 16 63  9 49 52 20] <class 'numpy.ndarray'>
[84 27 56 65  2 65 81  0  0 94] <class 'list'>


In [208]:
#adição
array1 + array2

array([150,  63, 109, 160,  18, 128,  90,  49,  52, 114])

In [209]:
array2[0] = 0
array2

array([ 0, 27, 56, 65,  2, 65, 81,  0,  0, 94])

In [213]:
#multiplicação
array1*array2

array([   0,  972, 2968, 6175,   32, 4095,  729,    0,    0, 1880])

In [214]:
array1@array2

16851

In [217]:
# divisão
array3 = array1 / array2
array3

<ipython-input-217-0d4946046079>:2: RuntimeWarning: divide by zero encountered in true_divide
  array3 = array1 / array2


array([       inf, 1.33333333, 0.94642857, 1.46153846, 8.        ,
       0.96923077, 0.11111111,        inf,        inf, 0.21276596])

In [218]:
[i for i in array3 if i != np.inf]

[1.3333333333333333,
 0.9464285714285714,
 1.4615384615384615,
 8.0,
 0.9692307692307692,
 0.1111111111111111,
 0.2127659574468085]

In [219]:
array3[array3 != np.inf]

array([1.33333333, 0.94642857, 1.46153846, 8.        , 0.96923077,
       0.11111111, 0.21276596])

In [223]:
np.array(list(filter(lambda x: x!=np.inf, array3)))

array([1.33333333, 0.94642857, 1.46153846, 8.        , 0.96923077,
       0.11111111, 0.21276596])

In [224]:
#concatenate
np.concatenate((array1, array2))

array([66, 36, 53, 95, 16, 63,  9, 49, 52, 20,  0, 27, 56, 65,  2, 65, 81,
        0,  0, 94])

In [227]:
np.concatenate((array1, array2))

array([66, 36, 53, 95, 16, 63,  9, 49, 52, 20,  0, 27, 56, 65,  2, 65, 81,
        0,  0, 94])

### Operações em arrays

### Problema 1:
Somar 2 Listas de tamanhos iguais - Retorno deve conter uma lista

In [228]:
import random
lista1 = random.sample(range(10), 10)
lista2 = random.sample(range(10), 10)
print(lista1, lista2, sep='\n')

[9, 6, 5, 1, 4, 3, 7, 8, 0, 2]
[1, 0, 5, 3, 2, 9, 7, 8, 6, 4]


In [230]:
#numpy
import numpy as np
array1 = np.array(lista1)
array2 = np.array(lista2)
array3 = array1+array2
array3

array([10,  6, 10,  4,  6, 12, 14, 16,  6,  6])

In [238]:
array = np.array(lista1)+np.array(lista2)
print(array.tolist())

[10, 6, 10, 4, 6, 12, 14, 16, 6, 6]


In [241]:
#list comprehension
[lista1[i]+lista2[i] for i in range(len(lista1))]

[10, 6, 10, 4, 6, 12, 14, 16, 6, 6]

In [242]:
#list comprehension + enumerate
[x+lista2[i] for i, x in enumerate(lista1)]

[10, 6, 10, 4, 6, 12, 14, 16, 6, 6]

In [243]:
#list comprehension + zip
[x+y for x, y in zip(lista1, lista2)]

[10, 6, 10, 4, 6, 12, 14, 16, 6, 6]

In [244]:
#map + lambda
list(map(lambda x,y: x+y, lista1, lista2))

[10, 6, 10, 4, 6, 12, 14, 16, 6, 6]

### problema 2
Somar 2 Arrays de tamanhos diferentes - Retorno deve conter um array

***Tomar cuidado ao fazer operações com arrays de tamanhos diferentes***

Ex: array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) + array([1, 1, 1, 1, 1]) = array(2, 3, 4, 5, 6, 6, 7, 8, 9, 10)

In [245]:
lista1 = np.random.randint(0,100,10)
lista2 = np.random.randint(0,100,5)
print(lista1, type(lista1))
print(lista2, type(lista2))

[65 53 49 43 70 73 17 78 65 60] <class 'numpy.ndarray'>
[29 62 53 17 33] <class 'numpy.ndarray'>


In [246]:
lista1+lista2

ValueError: operands could not be broadcast together with shapes (10,) (5,) 

In [247]:
lista1.shape

(10,)

In [248]:
lista2.shape

(5,)

In [253]:
lista1+np.concatenate((lista2, np.zeros( lista1.shape[0] - lista2.shape[0] )))

array([ 94., 115., 102.,  60., 103.,  73.,  17.,  78.,  65.,  60.])

### Métodos

In [266]:
lista1 = np.random.randint(0,100,10)
lista1

array([25, 97, 69, 22, 31,  4,  7, 61, 62, 18])

In [267]:
#maior valor
lista1.max()

97

In [268]:
#index do maior valor
lista1.argmax()

1

In [269]:
#menor valor
lista1.min()

4

In [270]:
#index do menor valor
lista1.argmin()

5

In [271]:
#soma de todos os items
lista1.sum()

396

In [260]:
#media
lista1.mean()

49.6

In [261]:
#desvio padrão
lista1.std()

27.749594591633226

In [262]:
listax = sorted(lista1)
print(lista1)
print(listax)

[96 52 29 63 42  1 37 26 91 59]
[1, 26, 29, 37, 42, 52, 59, 63, 91, 96]


In [272]:
#ordenar a lista
lista1.sort()
lista1

array([ 4,  7, 18, 22, 25, 31, 61, 62, 69, 97])

In [273]:
## Aleatorizando o array

lista1 = np.random.permutation(lista1)

## ou
random.shuffle(lista1)

lista1

array([61, 69, 22, 97, 31,  4, 62, 18, 25,  7])

In [274]:
#Trocando o tipo dos dados nas lista
lista1 = lista1.astype(int)
lista1

array([61, 69, 22, 97, 31,  4, 62, 18, 25,  7])

In [277]:
lista1

array([69, 69, 22, 97, 31,  4, 62, 18, 25,  7])

In [279]:
np.unique(lista1, return_counts=True)

(array([ 4,  7, 18, 22, 25, 31, 62, 69, 97]),
 array([1, 1, 1, 1, 1, 1, 1, 2, 1], dtype=int64))

In [280]:
# Valores únicos
values, count = np.unique(lista1, return_counts=True)

values[count.argmax()]

69

In [281]:
#moda
import statistics
statistics.mode(lista1)

69

### Matriz

In [285]:
#Criando matriz
matriz = np.matrix('1 2 1; 3 4 1;5 6 1')
matriz

matrix([[1, 2, 1],
        [3, 4, 1],
        [5, 6, 1]])

In [286]:
np.matrix([[1, 2],[3, 4]])

matrix([[1, 2],
        [3, 4]])

In [292]:
#Matriz de zeros
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [293]:
#Matriz de 1's
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [294]:
#eye - Matriz identidade
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [295]:
listaD = np.arange(0,20,2)
listaD

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### Operações

In [296]:
# Redimensionamento
matriz = listaD.reshape(5, 2)
matriz

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [297]:
matriz.shape

(5, 2)

In [300]:
#Matriz Transposta
matriz.T

##ou
matriz.transpose()

array([[ 0,  4,  8, 12, 16],
       [ 2,  6, 10, 14, 18]])

In [299]:
matriz.T.shape

(2, 5)

In [311]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [319]:
#concatenaçäo
np.concatenate((np.ones((5,1)), matriz), axis=1)

array([[ 1.,  0.,  2.],
       [ 1.,  4.,  6.],
       [ 1.,  8., 10.],
       [ 1., 12., 14.],
       [ 1., 16., 18.]])

In [314]:
#hstack
np.hstack((np.ones(10).reshape(5,2), matriz))

array([[ 1.,  1.,  0.,  2.],
       [ 1.,  1.,  4.,  6.],
       [ 1.,  1.,  8., 10.],
       [ 1.,  1., 12., 14.],
       [ 1.,  1., 16., 18.]])

In [318]:
#vstack
np.vstack((np.ones(2), matriz))

array([[ 1.,  1.],
       [ 0.,  2.],
       [ 4.,  6.],
       [ 8., 10.],
       [12., 14.],
       [16., 18.]])

In [320]:
matriz

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [ ]:
#indexação matriz
matriz[2:,1:]

# Paramos aqui

### Problema 3: 

Criar uma matriz 10x2 onde na primeira coluna estejam os valores de [1..10] e a segunda coluna seja preenchida com zeros

In [321]:
lista = []
for i in range(1, 11):
    lista.append([i, 0])
np.array(lista)

array([[ 1,  0],
       [ 2,  0],
       [ 3,  0],
       [ 4,  0],
       [ 5,  0],
       [ 6,  0],
       [ 7,  0],
       [ 8,  0],
       [ 9,  0],
       [10,  0]])

#### Solução 1 - Usando Pandas

In [ ]:
import pandas as pd

In [ ]:
valores = np.array(range(1,11))
valores.reshape(10,1)
valores

**Vamos criar um dataframe com o formato que desejamos e depois converte-lo para numpy array**

In [ ]:
df = pd.DataFrame({'A': valores, 'B':np.zeros(10)})
df

In [ ]:
df.to_numpy()

#### Solução 2 - Usando hstack

In [ ]:
np.hstack((valores.reshape(10,1), np.zeros(10).reshape(10,1)))

#### Solução 3 - Usando vstack e matriz transposta

In [ ]:
arr = np.vstack((valores, np.zeros(10)))
arr

In [ ]:
# .T gera a matriz transposta ou seja, linha vira coluna
arr.T

#### Solução 4 - Usando concatenate

In [ ]:
np.concatenate((valores.reshape(10,1), np.zeros((10,1))), axis=1)

### Máscaras

In [ ]:
aleatorio

In [ ]:
#Mascaras
aleatorio > 0.5

In [ ]:
aleatorio[~(aleatorio > 0.5)]

In [ ]:
lista10

In [ ]:
#Numeros pares
pares = lista10 % 2 == 0
pares

In [ ]:
#Aplicando a mascara a mastriz
lista10[pares]

In [ ]:
#Aplicando a mascara maior que 2
lista10[lista10>2]

## Pandas

### Series

`Series` representam as colunas das tabelas, guardando seu conteúdo com numpy arrays, porem neste caso cada array tem um index, que permite acessar o conteúdo das series como um similar a um dicionário python. além disso essa classe conta com alguns métodos mais avançados que o numpy array.

In [ ]:
import pandas as pd

In [ ]:
#utilizando um lista simples
minha_lista = [10,20,30]
serie = pd.Series(minha_lista)
serie

In [ ]:
serie.loc[2]

In [ ]:
arr = np.array(minha_lista)

In [ ]:
arr[1]

In [ ]:
#Acessando dados como um lista
serie[1]

In [ ]:
#indexação
serie[:2]

In [ ]:
#Series com index
labels = ['a','b','c','e']
lista4 = [10,20,30,40]
serieLabel = pd.Series(data=lista4,index=labels)
serieLabel

In [ ]:
#acessando index 'a' da serie
serieLabel['a']

In [ ]:
#acessando index 'a' e 'b' da serie
serieLabel['a':'b']

In [ ]:
#Series com dicionarios
dicionario = {'a':10,'b':20,'c':30}
pd.Series(dicionario)

In [ ]:
#operações com series
dic1 = {"Brasil":10,"EUA":10,"Japão":10}
serie1 = pd.Series(dic1)
dic2 = {"Brasil":10,"Bolivia":10,"Japão":10}
serie2 = pd.Series(dic2)
serie1 + serie2

In [ ]:
#unique
serie1 = pd.Series(['a','b','c','a','d','e','c','a','e','d'])
serie1.unique()

In [ ]:
#Contando valores
serie1.value_counts().sort_index()/len(serie1)

In [ ]:
#isin - Para filtar valores
mask = serie1.isin(['b', 'c'])
mask

serie1[mask]

### Dataframe

E por ultimo temos a estrutura DataFrame, esta será nossa tabela, representada por um dicionário de series com o mesmo index.

In [ ]:
np.random.seed(42) #Para o rand ficar igual

lista = np.random.randn(5,3)
lista

In [ ]:
pd.DataFrame(lista)

In [ ]:
index = ['a','b','c','d','e']
colunas = ['x','y','z']
dataFrame = pd.DataFrame(data = lista,index=index,columns=colunas)
dataFrame

In [ ]:
# acessando coluna 'x', retornando uma serie
dataFrame['x']

In [ ]:
# acessando colunas 'x' e 'y', retornando um dataframe
dataFrame[['x','y']]

In [ ]:
#pegando ponto
dataFrame['x']['a']

In [ ]:
#Pegando linha
dataFrame.loc['a']

In [ ]:
#Pegando linha por numero
dataFrame.iloc[0]

In [ ]:
#pegando linha e colunuma
dataFrame.loc['a','x']

In [ ]:
dataFrame.loc[['a','c'],['x','y']]

In [ ]:
#nova coluna 
dataFrame['novo'] = dataFrame['x'] + dataFrame['y']
dataFrame

In [ ]:
#remove mas não salva
dataFrame.drop('novo',axis=1)

In [ ]:
dataFrame

In [ ]:
#remove e salva
dataFrame.drop('novo',axis=1,inplace=True)
dataFrame

In [ ]:
#retirando colunas
dataFrame.drop('e')

In [ ]:
#Seleções através de condições
dataFrame>0

In [ ]:
#utilizando condição como mascara para um novo dataFrame
dataFrame[dataFrame>0]

In [ ]:
#porem não salva
dataFrame

In [ ]:
#retira a linha do y que tem um item menor que 0
dataFrame[dataFrame['y']>0]

In [ ]:
#Mesma operação de cima porem so retorna o linha z
dataFrame[dataFrame['y']<0]['z']

In [ ]:
dataFrame

In [ ]:
#resetando index
dataFrame.reset_index()

In [ ]:
#resetando index sem manter o index antigo
dataFrame.reset_index(drop=True)

In [ ]:
dataFrame['nomes'] = ['SP','RJ','BH','SSA','NV']

In [ ]:
dataFrame

In [ ]:
#reordenando as colunas

dataFrame = dataFrame[['x', 'nomes', 'y', 'z']]
dataFrame

In [ ]:
#Alterando o nome das colunas
dataFrame.columns = ['x', 'estados', 'y', 'z']
dataFrame

In [ ]:
#criando novo index
dataFrame.set_index('estados',inplace=True)

dataFrame

In [ ]:
dataFrame.loc['SP']

**indices multiplos**

In [ ]:
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index

In [ ]:
hier_index = pd.MultiIndex.from_tuples(hier_index)

hier_index

In [ ]:
matriz = np.random.randn(6,2)
matriz

In [ ]:
df = pd.DataFrame(matriz,index=hier_index,columns=['A','B'])

df

In [ ]:
df.loc['G1', 1]

In [ ]:
df.xs('G1')

#### Concats e merges

In [ ]:
df1 = pd.DataFrame({'A':[1,2,3],'B':[4,5,6],'C':[7,8,9]},index=['w','x','y'])
df2 = pd.DataFrame({'B':[1,2,3],'C':[4,5,6],'D':[7,8,9]},index=['x','y','z'])

In [ ]:
df1

In [ ]:
df2

In [ ]:
pd.concat([df1,df2])

In [ ]:
pd.concat([df1,df2],join='inner')

In [ ]:
pd.concat([df1,df2],axis=1)

In [ ]:
pd.concat([df1, df2], axis=1, join='inner')

In [ ]:
df3 = pd.DataFrame({'Paises':['Br','Pt','Bo'],'valor1':[1,2,3],"Valor2":[3,4,5]})
df4 = pd.DataFrame({'Paises':['Br','Pt','Bo'],'valor1':[1,2,3],"Valor4":[3,4,5]})

df3 

In [ ]:
df4

In [ ]:
pd.merge(df3, df4, on='Paises')

#### Importando dados

In [ ]:
filename = '../datasets/imoveis_Rio_de_Janeiro.csv'
df_imoveis_rj = pd.read_csv(filename, sep=';', nrows=0)
df_imoveis_rj.columns

In [ ]:
df_imoveis_rj = pd.read_csv(filename, sep=';', nrows=10)
df_imoveis_rj.head()

In [ ]:
df_imoveis_rj = pd.read_csv(filename, sep=';', usecols=['condominio', 'quartos', 'suites', 'vagas', 'area', 'bairro'])
df_imoveis_rj.head()

In [ ]:
df_imoveis_rj = pd.read_csv(filename, sep=';')
df_imoveis_rj.head()

#### Nan Values

In [ ]:
#Drop nan
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

In [ ]:
df.dropna(subset=['col2'])

In [ ]:
df

In [ ]:
df['col1'] = df['col1'].fillna(0)
df

In [ ]:
np.mean(df['col2'])

In [ ]:
df['col2'] = df['col2'].fillna(df['col2'].mean())
df